"""empty message

Revision ID: fb83113a2096
Revises: 3ccacdebb2df
Create Date: 2023-07-07 04:44:47.132982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb83113a2096'
down_revision = '3ccacdebb2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(), nullable=True))
        batch_op.drop_column('token_exp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
